import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { registerWorkflowExecuteTools } from "./workflow-execute.js";
import { registerWorkflowVisualizeTools } from "./workflow-visualize.js";
import { registerWorkflowComposeTools } from "./workflow-compose.js";
import { registerWorkflowValidateTools } from "./workflow-validate.js";
import { registerQueueManagementTools } from "./queue-management.js";
import { registerRegistrySearchTools } from "./registry-search.js";
import { registerModelManagementTools } from "./model-management.js";
import { registerModelExtrasTools } from "./model-extras.js";
import { registerSkillGeneratorTools } from "./skill-generator.js";
import { registerDiagnosticsTools } from "./diagnostics.js";
import { registerWorkflowLibraryTools } from "./workflow-library.js";
import { registerProcessControlTools } from "./process-control.js";
import { registerImageManagementTools } from "./image-management.js";
import { registerMemoryManagementTools } from "./memory-management.js";
import { registerGenerationTrackerTools } from "./generation-tracker.js";
import { registerAssetTools } from "./assets.js";
import { registerAutoloadedWorkflows } from "./workflow-autoload.js";
import { registerDefaultsTools } from "./defaults.js";
import { registerGenerateImageTool } from "./generate-image.js";
import { registerGenerateAudioTool } from "./generate-audio.js";
import { registerConditionedGenerationTools } from "./generate-conditioned.js";
import { registerWorkflowDslTools } from "./workflow-dsl.js";
import { registerNodeSnapshotsTools } from "./node-snapshots.js";
import { registerNodeBisectTools } from "./node-bisect.js";
import { registerNodeManagementTools } from "./node-management.js";
import { registerNodeAuthoringTools } from "./node-authoring.js";
import { registerNodeVerifyTools } from "./node-verify.js";
import { registerWorkflowDepsTools } from "./workflow-deps.js";
import { registerInstallComfyUITools } from "./install-comfyui.js";
import { registerUpdateComfyUITools } from "./update-comfyui.js";
import { registerWorkspaceEnvTools } from "./workspace-env.js";
import { registerApiNodesTools } from "./api-nodes.js";
import { registerManagerConfigTools } from "./manager-config.js";
import { registerManifestTools } from "./manifest.js";
import { registerImageConvertTools } from "./image-convert.js";
import { registerStorageUploadTools } from "./storage-upload.js";
import { registerHealthCheckTools } from "./health-check.js";
import { registerWorkflowLockTools } from "./workflow-lock.js";
import { DefaultsManager } from "../services/defaults-manager.js";

export async function registerAllTools(server: McpServer): Promise<void> {
  // Hydrate persisted defaults before any tool registration so subsequent
  // tools can consult DefaultsManager.apply() against a fully-resolved view.
  await DefaultsManager.load();
  registerWorkflowExecuteTools(server);
  registerWorkflowVisualizeTools(server);
  registerWorkflowComposeTools(server);
  registerWorkflowValidateTools(server);
  registerQueueManagementTools(server);
  registerRegistrySearchTools(server);
  registerModelManagementTools(server);
  registerSkillGeneratorTools(server);
  registerDiagnosticsTools(server);
  registerWorkflowLibraryTools(server);
  registerProcessControlTools(server);
  registerImageManagementTools(server);
  registerMemoryManagementTools(server);
  registerGenerationTrackerTools(server);
  registerAssetTools(server);
  registerDefaultsTools(server);
  registerGenerateImageTool(server);
  registerGenerateAudioTool(server);
  registerConditionedGenerationTools(server);
  registerWorkflowDslTools(server);
  registerNodeSnapshotsTools(server);
  registerNodeBisectTools(server);
  registerNodeManagementTools(server);
  registerWorkflowDepsTools(server);
  registerInstallComfyUITools(server);
  registerUpdateComfyUITools(server);
  registerModelExtrasTools(server);
  registerWorkspaceEnvTools(server);
  registerApiNodesTools(server);
  registerManagerConfigTools(server);
  registerNodeAuthoringTools(server);
  registerNodeVerifyTools(server);
  registerManifestTools(server);
  registerImageConvertTools(server);
  registerStorageUploadTools(server);
  registerHealthCheckTools(server);
  registerWorkflowLockTools(server);
  await registerAutoloadedWorkflows(server);
}
